### ISSUE TITLE
Adding a switch on GUI interface in order to control cropping options

### ISSUE THREAD

**Issue by lepoulet44** [darodi/kcc#18]
Hi.
Thanks for adding scribe profile to kcc. And many thanks for keeping this nice tool up to date.

Would it be possible to add a switch on gui interface in order to control the cropping options? (disable, margin, margin+page numbers)

(Understood that it is availabe on CLI version but my super noob skillls didn't allow me to make it work)

**Comment by darodi** [comment]
Hello @lepoulet44 

By default, the GUI is using those options: 
- cropping: Margins + page numbers
- cropping power 1.0

Is this not good enough for you?

```
    -c CROPPING, --cropping=CROPPING
                        Set cropping mode. 0: Disabled 1: Margins 2: Margins +
                        page numbers [Default=2]
    --cp=CROPPINGP, --croppingpower=CROPPINGP
                        Set cropping power [Default=1.0]
```

**Comment by lepoulet44** [comment]
Thanks a lot for your time and your hard work.

Most of the time, converting mangas or comics, the default cropping options are perfect and i wouldn't change them. Especially on a small device.

But for some graphic novels, in rare occasions, it can ruin the intention of the artists, zooming and centering small details on a blank page.

Some larger devices, like the kindle Scribe or the kobo Elipsa are now available,  and perhaps the possibility to keep the exact aspect of the pages could make sense on big screens?

**Comment by darodi** [comment]
I'll have a look to add that option in the GUI

**Comment by 4AM-Campfire** [comment]
An option to completely disable cropping would be welcome.

Removing the intentional white space from pages makes for a very jarring reading experience with layouts that make use of it.
