### ISSUE TITLE
No support for ZIPs

### ISSUE THREAD

**Issue by Sillyvan** [darodi/kcc#2]
The original software allows me to upload zip files. this dosent. why is that the case?

**Comment by darodi** [comment]
Could you elaborate on this?
Which version?
What is your platform?  Windows 10? Windows 11? Linux? MacOS? Other?
Do you use the built version or sources?
How do you reproduce the problem?

**Comment by darodi** [comment]
Works fine 
see screenshot.

This issue is closed. Reopen if needed, but with a correct description this time


![image](https://user-images.githubusercontent.com/4682830/204357656-7779e880-deb7-42dd-80ff-ed268bc756be.png)

**Comment by darodi** [comment]
@Sillyvan 

don't forget to install 7zip

- install 7zip
  ```bash
  $ sudo apt-get install -y p7zip-full
  ```
