### ISSUE TITLE
Spread splitter not keeping aspect ratio

### ISSUE THREAD

**Issue by Zaphain** [darodi/kcc#27]
When using split and rotate, regardless whether upscaling is set to keep the aspect ratio, the resulting three images will all be stretched to the full resolution. I'm unsure if this is a bug in behavior or whether I should be asking for an added option to have the aspect ratio preserved here and the images instead be centered.

**Comment by darodi** [comment]
@Zaphain 

Do you have an input example ?

**Comment by Zaphain** [comment]
https://imgur.com/a/XQ0QNIR
On closer look, it seems the rotated image is fine, it's just the split ones. Those are definitely stretched. The correct aspect ones were just done in imagemagick to show what I think it should be. (There's a typo in one of the image descriptions, but nevermind that, you can tell what I mean)

Also, I think if you wanted to keep more of the feeling of the pages being connected, you could left align image b, and right align image c. That might be best instead of centered.

**Comment by xMonTersx** [comment]
I could confirm that issue happen to me too.
I run KCC in webtoon mode, option Strech/upscale had been auto-checked, but the ratio of the result are not keep

**Comment by darodi** [comment]
@Zaphain 

I'm unable to reproduce your problem.
With those settings:
![image](https://user-images.githubusercontent.com/4682830/210113743-df734f19-c08c-4ca4-82bb-09d2301398aa.png)

I get the following, where orig.jpg is the original image
[result.zip](https://github.com/darodi/kcc/files/10326351/result.zip)

**Comment by Zaphain** [comment]
> ...With those settings: ![image](https://user-images.githubusercontent.com/4682830/210113743-df734f19-c08c-4ca4-82bb-09d2301398aa.png)

Okay, I see where the issue is, this doesn't happen when epub is chosen as the output, it's only affecting the KFX output. https://imgur.com/a/uqDTyo7

**Comment by darodi** [comment]
OK, it must be here in the code.
KFX mode is stretching for split images 

https://github.com/darodi/kcc/blob/88ffcefa6649e2d2a16812479691892c4a1ad186/kindlecomicconverter/image.py#L312-L313

**Comment by darodi** [comment]
I've tested with Calibre and `KFX Conversion Output Plugin` without the stretch.
It works. I'll commit this and make a new release.
I must admit I've never used the KFX output before, only MOBI files.

**Comment by xMonTersx** [comment]
@darodi 
Could you please check this issues with these setting. The ratio is not keep
![image](https://user-images.githubusercontent.com/10475907/210302201-1b35ebb4-c941-48db-bf02-6475b507ad51.png)
