### ISSUE TITLE
Image aspect ratio is not kept in webtoon mode

### ISSUE THREAD

**Issue by xMonTersx** [darodi/kcc#29]
version: KCC_5.5.3b18
setting:
![image](https://user-images.githubusercontent.com/10475907/210326934-d35465a8-22b6-4265-8924-b072213881d3.png)
image source and result
[test.zip](https://github.com/darodi/kcc/files/10335343/test.zip)
Please help me check out this issues

**Comment by xMonTersx** [comment]
@darodi Could you reproduct this issue?

**Comment by darodi** [comment]
@xMonTersx 

I don't own a PW4 anymore.
I've tried your input with your setting and my reader, everything seems OK.
Could you post a photo of your reader with the incorrect ratio?

----

The code is here
The height ratio is computed between the horizontal output size and the horizontal input size.
Then the new width size is computed using the same ratio.
The resize uses, the new width and the horizontal output size.

https://github.com/darodi/kcc/blob/b6080969cd2d998dfd8ad8e65f0360a45bf7e719/kindlecomicconverter/image.py#L333-L335

**Comment by xMonTersx** [comment]
@darodi 
Sorry, It's my mistake. I had checked the results via calibre viewer.
everthing is ok with my device
