### ISSUE TITLE
Option to have PNG instead of jpg images

### ISSUE THREAD

**Issue by MilesTEG1** [darodi/kcc#3]
Hello,
Nice work for adding mozjpg and kobo libra H2O specs.

Is it possible to add an option to have png instead of jpg images ? with option to set compression.

Thanks :)

**Comment by darodi** [comment]
@MilesTEG1 

There is already an option for that in the command line app
https://github.com/darodi/kcc#standalone-kcc-c2epy-usage
`  --forcepng          Create PNG files instead JPEG`

Do you mean in the GUI interface?

**Comment by MilesTEG1** [comment]
> Do you mean in the GUI interface?

Yes I lean in the gui ☺️

**Comment by darodi** [comment]
OK I'll add that

**Comment by darodi** [comment]
done
see https://github.com/darodi/kcc/releases/tag/v5.5.3-beta-darodi.6

However, I won't add a slider for "compression" option right now. It might give undesired side effects, especially if used with mozJpeg.


![image](https://user-images.githubusercontent.com/4682830/194420787-f779b3dc-a1bd-4bcf-b22f-a1c02bc32f9a.png)

**Comment by darodi** [comment]
@MilesTEG1 

can this be closed?

**Comment by MilesTEG1** [comment]
@darodi Yes thank you very much :)
