### ISSUE TITLE
https://aur.archlinux.org/packages/kcc-beta to update

### ISSUE THREAD

**Issue by darodi** [darodi/kcc#36]
Hello @celogeek

Here you created a repository for ARCH.
https://github.com/darodi/kcc/issues/21#issuecomment-1364013077

I think
https://aur.archlinux.org/packages/kcc-beta
should be updated, I changed the required versions for slugify, 
This https://aur.archlinux.org/cgit/aur.git/tree/kcc-slugify.patch?h=kcc-beta 
is not required anymore.

**Comment by celogeek** [comment]
Thanks !
I've update the beta.
I was highly focus on my go version ;)

**Comment by darodi** [comment]
Thanks a lot!

>  I was highly focus on my go version ;)

I've seen. It's shaping up! If you add double page splitting and manga mode, all the basic stuff will be there. 👍

**Comment by celogeek** [comment]
For double page, I add autoRotate option. If width > height, it rotate the image instead of cutting it in the middle.
I can see the double page on LANDSCAPE mode, which I prefer a lot.
For manga mode, yes, I will need to rewrite the content.opf to make it write.
I add that to my list ;)

**Comment by darodi** [comment]
I usually use both, a preview rotated and both split images.
It's sometimes too small to read on the double page rotated. :)
