### ISSUE TITLE
[Feature Request] Automatic Conversion + UI on container

### ISSUE THREAD

**Issue by hvmzx** [darodi/kcc#38]
Hello,

Using the docker container, unfortunately it doesn't run the UI but just the command (which is the expected behavior)
Would it be possible to have run KCC on a port and be usable from there ? 

And is there a way to have it run in the background and automatically convert ebooks matching a certain regex or in a specific folder and convert them without doing it manually every time ?

Thanks for your work !

**Comment by darodi** [comment]
Hello @HamzaM 

I'll have a look.

Another idea, on the docker host, you could also use a crontab (on linux or on WSL) or the Windows Task Scheduler to launch a periodic command that will launch the docker on a specific directory.

**Comment by darodi** [comment]
or extend the docker image to add a crontab in it.

**Comment by hvmzx** [comment]
> docker

Oh didn't know we could watch a folder that way, I'll look into it

**Comment by darodi** [comment]
@HamzaM 

Were you able to put a solution in place?
Do you still need some help about this?

**Comment by darodi** [comment]
@HamzaM 

no news
closing this.
reopen an issue in 
https://github.com/ciromattia/kcc
if needed.

**Comment by hvmzx** [comment]
I left it alone all this time, will try the cron method and let you know
