### ISSUE TITLE
Even with EPUB-200MB option selected, created file is above 200MB

### ISSUE THREAD

**Issue by FlorentMartinPilot** [darodi/kcc#44]
Hi !

I had a trouble with converting a file. The original was a 664 MB file, and the output gave me 3 files :

The first file is 209 007 485 
The second is 210 222 573
The third is 2 824 351

The second file was rejected by the website Send To Kindle because it was above the 200MB limit (200.5MB)

Thanks for this great program anyway !

**Comment by darodi** [comment]
OK the limit was in mebibyte (MiB).
I've adapted it to 195 MiB.

**Comment by FlorentMartinPilot** [comment]
Thanks a lot !

**Comment by darodi** [comment]
https://github.com/darodi/kcc/releases/tag/v5.6.2b4

will be available in a few minutes

**Comment by FlorentMartinPilot** [comment]
AMAZING job, congrats !
