### ISSUE TITLE
create docker image

### ISSUE THREAD

**Issue by darodi** [darodi/kcc#5]
Docker images would be great for command line 

- should be multi-arch
- should not contain kindlegen, but can be added with a mount
- armv7 support with QEMU

**Comment by hhtien1408** [comment]
Waiting for your docker images. Atm I am using Saoula's docker images.
[https://hub.docker.com/r/saoula/kcc](url)

**Comment by darodi** [comment]
@hhtien1408 

A first docker image is present, but it works only with command line for the moment.
I still have to test it and adapt it for the GUI.


[image https://github.com/darodi/kcc/pkgs/container/kcc](https://github.com/darodi/kcc/pkgs/container/kcc)
[usage https://github.com/darodi/kcc#docker](https://github.com/darodi/kcc#docker)

**Comment by darodi** [comment]
I also have to test armv7 with QEMU

**Comment by hhtien1408** [comment]
Great! I will test CLI and wait for GUI docker.
