### ISSUE TITLE
Linux beta version?

### ISSUE THREAD

**Issue by it0na72** [darodi/kcc#6]
Would love to use the Kobo presets on my Pop_OS 22.04. Would this be possible? Automatic conversion to Kepub is really good.

**Comment by darodi** [comment]
@it0na72 

while waiting for a docker image and a appImage, you could try using kcc from sources

https://github.com/darodi/kcc#usage-from-sources

**Comment by darodi** [comment]
@it0na72 

appImage and binary is available for Linux 😄
https://github.com/darodi/kcc/releases

Docker image is available
https://github.com/darodi/kcc/pkgs/container/kcc

testPypi installation is possible too
https://test.pypi.org/project/KindleComicConverterDarodi/

see documentation here

- https://github.com/darodi/kcc#binary-releases
- https://github.com/darodi/kcc#pypi
- https://github.com/darodi/kcc#appimage
- https://github.com/darodi/kcc#docker


Test and feedback is welcome with Pop_OS. 
I haven't installed a vagrant image yet to test it. 😅

**Comment by darodi** [comment]
@it0na72 

Were you able to test this?

**Comment by darodi** [comment]
AppImage tested on `pop_os-21.04` with vagrant vm
works fine

**Comment by lennie420** [comment]
Hi @darodi just wanted to thank you for this, I actually tested the other day on Arch Linux and it worked. Forgot to reply here though. I appreciate your effort. Peace, love and happiness!

**Comment by it0na72** [comment]
> @it0na72 
> 
> Were you able to test this?

Yes sorry for the delay! Tested and works perfectly!
