### ISSUE TITLE
KFX Output in GUI

### ISSUE THREAD

**Issue by nodymoha** [darodi/kcc#9]
Thank you for your excellent work on updating this software.

If you have the time, I have a small request I think you can manage easily.

Can you add KFX as an output file format in the GUI?

This option will produce a clean EPUB file manageable by Calibre to be converted to KFX format using the KFX Output plugin.

This feature is available in the CLI version but not in the GUI version.

**Comment by darodi** [comment]
@nodymoha 
done

the release/docker will be available in a few minutes.
